# Generated by Django 2.2 on 2021-07-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adv_Name', models.CharField(blank=True, max_length=300)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=300)),
                ('item_name', models.CharField(max_length=300)),
                ('Quantity', models.CharField(max_length=300)),
                ('Price', models.CharField(max_length=300)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Direction_x', models.IntegerField(blank=True, null=True)),
                ('Direction_y', models.IntegerField(blank=True, null=True)),
                ('Category', models.CharField(choices=[('1', 'Cold Drink'), ('2', 'Chips'), ('3', 'Burger'), ('4', 'Milk'), ('5', 'Vegetables')], default='1', max_length=20)),
                ('Ratings', models.CharField(choices=[('1', 'Not Liked'), ('2', 'Better'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Outstanding')], default='1', max_length=20)),
            ],
        ),
    ]
