# Generated by Django 2.2 on 2021-07-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
