# Generated by Django 2.2 on 2021-07-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcart', '0002_items_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
