# Generated by Django 2.2 on 2021-07-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcart', '0003_auto_20210727_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
